In [1]:
print("Hello")


Hello


In [2]:
print("How are you")

How are you


In [3]:
def hello():
    print("Hi there how are you")

In [4]:
hello()

Hi there how are you


In [2]:
import numpy as np

- Basic Array Creation in numpy

In [21]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [23]:
# creating a list
l = [4,5,6,"hello"]
l

[4, 5, 6, 'hello']

In [24]:
np.array(l)

array(['4', '5', '6', 'hello'], dtype='<U21')

In [25]:
list = [[1,2,3],[4,5,6],[7,8,9]]

* Array Generation Functions:

In [26]:
np.array(list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
arr = np.arange(1,10,2)
arr

array([1, 3, 5, 7, 9])

In [36]:
arr = np.zeros((6,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [41]:
arr = np.ones((4,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [6]:
arr = np.linspace(1,5,3)
arr

array([1., 3., 5.])

In [ ]:
arr = np.linspace(0,1,100) 
# 0 is a starting part 
# 1 end range part. 
# 100 is how many element that i want it will print 100 numbers b/w 0-1 100 
# 100 numbers with linear step or linear space actually same step with every number
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

- Random ganeration Function

In [87]:
np.random.rand(10)

array([0.83614632, 0.50156874, 0.27672366, 0.90473983, 0.05918806,
       0.72094316, 0.85927178, 0.42898864, 0.61609222, 0.78157406])

In [1]:
import numpy as np


In [113]:
np.random.randn(10)

array([-0.1461009 ,  0.49749724,  0.22238125, -0.52534397, -2.77013818,
        0.83646055,  1.25569357,  0.51858731,  0.71133304,  0.29484931])

In [7]:
a=np.random.randint(10,20, 100)
a

array([17, 12, 13, 11, 13, 19, 11, 19, 15, 10, 13, 15, 12, 18, 14, 19, 17,
       14, 14, 10, 13, 15, 10, 10, 17, 16, 17, 17, 16, 13, 13, 18, 14, 16,
       17, 19, 12, 15, 12, 18, 14, 14, 19, 17, 12, 12, 19, 15, 18, 16, 14,
       10, 18, 12, 13, 16, 12, 11, 10, 18, 17, 10, 15, 19, 18, 13, 14, 16,
       15, 13, 17, 17, 11, 16, 10, 14, 13, 10, 19, 14, 13, 10, 13, 18, 18,
       17, 15, 14, 12, 13, 17, 13, 10, 19, 14, 16, 11, 10, 11, 10],
      dtype=int32)

In [2]:
import numpy as np

In [8]:
arr = np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
print(arr.shape)

(3, 3)


In [14]:
print(arr.size)

9


In [15]:
print(arr.dtype)

int64


- Array Methods

In [16]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
print(arr.min())

1


In [18]:
print(arr.max())

9


In [19]:
print(arr.sum())

45


In [20]:
np.sum(arr,axis = 0) # 12 first colum sum 15-2nd col, 18-3rd col
# for colum wise sum

array([12, 15, 18])

In [ ]:
np.sum(arr,axis = 1) # row wise sum for each 
# row 1 = 6
# row 2 = 15
# row 3 = 24


array([ 6, 15, 24])

In [21]:
arr.mean()

np.float64(5.0)

In [22]:
arr.std()

np.float64(2.581988897471611)

In [23]:
arr.argmin() # minimum index

np.int64(0)

In [24]:
print(arr.argmax()) # max index

8


In [25]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [26]:
arr = arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [45]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [46]:
arr[6]

np.int64(17)

In [47]:
arr[0:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [48]:
arr[::-1]

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11])

In [49]:
arr[1:6]

array([12, 13, 14, 15, 16])

In [50]:
arr[0]

np.int64(11)

In [51]:
arr[3::2]

array([14, 16, 18, 20])

- Numpy Indexing and Slicing of Matrix:

In [52]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [53]:
arr[0,0]

np.int64(1)

In [54]:
arr[0,1], arr[0,2],arr[0,3],arr[0,4]

(np.int64(2), np.int64(3), np.int64(4), np.int64(5))

In [55]:
arr[0],arr[1] # it will print the matrix index rows

(array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10]))

In [76]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [77]:
arr[0:2, 1:3]

array([[2, 3],
       [7, 8]])

In [84]:
slice = arr[3:,3:]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

- Slicing the colums, after that become the Vector

In [ ]:
arr[:, 2] # this is a vector now , colunm 2

array([ 3,  8, 13, 18, 23, 28])

- BOOLEAN INDEXING

In [66]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [67]:
bool_index = arr % 2 == 0
bool_index_odd = arr % 2 !=0

In [68]:
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [69]:
bool_index_odd

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [70]:
even = arr[bool_index] # even numbers
even


array([12, 14, 16, 18, 20])

In [72]:
odd = arr[bool_index_odd]
odd

array([11, 13, 15, 17, 19])

# Arrays Operations:-

##### Arthematic Operations:-

In [148]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [149]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [150]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [151]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [152]:
a1//a2

array([0, 0, 0, 0, 0])

In [153]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [154]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

#### Brodcasting:-

In [73]:
arr = np.array([10,20,30,40,50])
arr

array([10, 20, 30, 40, 50])

In [75]:
arr + 10
# '''
# add the 10 to the whole list each element with +10
# it's called the brodcasting:
# '''

array([20, 30, 40, 50, 60])

In [76]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [77]:
arr2 = arr2 + 10

In [78]:
arr2 * 2

array([[22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50],
       [52, 54, 56, 58, 60],
       [62, 64, 66, 68, 70]])

In [81]:
arr2 ** 2

array([[ 121,  144,  169,  196,  225],
       [ 256,  289,  324,  361,  400],
       [ 441,  484,  529,  576,  625],
       [ 676,  729,  784,  841,  900],
       [ 961, 1024, 1089, 1156, 1225]])

#### Shallow copy and Deep copy

In [82]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [83]:
slice = a[:5]
slice

array([1, 2, 3, 4, 5])

In [84]:
slice * 10

array([10, 20, 30, 40, 50])

In [85]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

Shallow copy

In [86]:
b=a.copy()

In [87]:
b 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [88]:
b[0]=100

In [89]:
b

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [90]:
a 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

Deep copy

In [91]:
a = b

In [92]:
a

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [93]:
b

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [94]:
b[0]=1

In [95]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [96]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

This is deep copy,change in b also lead to change in a 
__________________________________________________________


### Matrix Operation

In [97]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
a

array([[1, 2],
       [3, 4]])

In [198]:
b

array([[5, 6],
       [7, 8]])

In [ ]:
a * b # it will do the index wise multiplicaiton

array([[ 5, 12],
       [21, 32]])

In [98]:
# performing the matrix multiplicaiton
# first row a matrix first row b matrix first col 1,2
# second row a matrix first row b matrix first col 1,2

a @ b


array([[19, 22],
       [43, 50]])

In [99]:
np.dot(a,b)

array([[19, 22],
       [43, 50]])

Inverse(Transpose) the matrix means make rows to colum and col to rows

In [100]:
a 

array([[1, 2],
       [3, 4]])

In [102]:
a.T

array([[1, 3],
       [2, 4]])

In [104]:
b
b.T

array([[5, 7],
       [6, 8]])

#### Advance Array Manipulation

Stacking array

In [2]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

In [3]:
vs = np.vstack((a,b)) # Vertical Stack
vs

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [4]:
np.hstack((a,b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [240]:
np.column_stack((a,b))

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

Splitting array

In [1]:
import numpy as np

In [105]:
a1 = np.arange(16).reshape(4,4)
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [106]:
np.hsplit(a1,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [5]:
np.hsplit(a1,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [6]:
np.hsplit(a1,1)

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [7]:
np.vsplit(a1,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [8]:
np.vsplit(a1,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [9]:
for i in a1:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
