In [1]:
import numpy as np


In [4]:
s = np.array([
   [5, 3, 4, 6, 7, 8, 9, 1, 2],
   [6, 7, 2, 1, 9, 5, 3, 4, 8],
   [1, 9, 8, 3, 4, 2, 5, 6, 7],
   [8, 5, 9, 7, 6, 1, 4, 2, 3],
   [4, 2, 6, 8, 5, 3, 7, 9, 1],
   [7, 1, 3, 9, 2, 4, 8, 5, 6],
   [9, 6, 1, 5, 3, 7, 2, 8, 4],
   [2, 8, 7, 4, 1, 9, 6, 3, 5],
   [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [5]:
print(s.sum())

405


In [7]:
print(np.sum(s, axis=1)) # rows for sum axis is 1, colum 0

[45 45 45 45 45 45 45 45 45]


In [8]:
print(np.sum(s, axis=0))

[45 45 45 45 45 45 45 45 45]


In [9]:
b = np.sum(s, axis=1)
# b == 45
for i in b:
    if i != 45:
        print("Sudoko is not valid")
        break
else:
    print("Suduko is valid for rows")

Suduko is valid for rows


In [10]:
c = np.sum(s, axis=0)
# b == 45
for i in c:
    if i != 45:
        print("Sudoko is not valid")
        break
else:
    print("Suduko is valid for colums")

Suduko is valid for colums


In [11]:
s

array([[5, 3, 4, 6, 7, 8, 9, 1, 2],
       [6, 7, 2, 1, 9, 5, 3, 4, 8],
       [1, 9, 8, 3, 4, 2, 5, 6, 7],
       [8, 5, 9, 7, 6, 1, 4, 2, 3],
       [4, 2, 6, 8, 5, 3, 7, 9, 1],
       [7, 1, 3, 9, 2, 4, 8, 5, 6],
       [9, 6, 1, 5, 3, 7, 2, 8, 4],
       [2, 8, 7, 4, 1, 9, 6, 3, 5],
       [3, 4, 5, 2, 8, 6, 1, 7, 9]])

In [12]:
for i in range(0,9,3):
    for j in range(0,9,3):
       n= s[i:i+3, j:j+3]
       print(n.sum())

45
45
45
45
45
45
45
45
45


In [26]:
# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [27]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [28]:
#Find the average age of students.
avg_age = np.mean(data[:,0])
print("Avg age of the students is : ", avg_age)


Avg age of the students is :  18.4


In [29]:
data[:,1:2]

array([[85],
       [92],
       [76],
       [65],
       [90]])

In [30]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [31]:
#Find the highest Science mark
print(" Hightes Science marks:",np.max(data[:, 2]))
print(" Hightes Science marks:",np.max(data))

 Hightes Science marks: 95
 Hightes Science marks: 95


In [37]:
#Get details of the student who scored more than 90 in Math.
data[data[:, 1] >90,1]

array([92])

In [38]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [39]:
#Increase Math marks of all students by 5.
data[:,1]+=5

In [40]:
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [42]:
#Find how many students are younger than 19.
print("all student age:", data[:,0 ]) 
print("Those are less than 19:")
print(data[data[:,0 ] < 19])
# the question total how many:
print("Total students are less than 19 is:",len(data[data[:,0 ] < 19]))


all student age: [18 19 17 18 20]
Those are less than 19:
[[18 90 78]
 [17 81 95]
 [18 70 70]]
Total students are less than 19 is: 3


In [46]:
#Calculate the average marks in each subject (column-wise mean).
mean1 = data[:, 1:3]
mean1

array([[90, 78],
       [97, 88],
       [81, 95],
       [70, 70],
       [95, 85]])

In [49]:
np.mean(data[:, 1:], axis=0)

array([86.6, 83.2])

In [57]:
#Get data of students who scored at least 80 in both subjects.
data[(data[:, 1] >=80) & (data[:, 2] >=80), 1:3 ]

array([[97, 88],
       [81, 95],
       [95, 85]])

In [58]:
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [60]:
#Replace all Science marks < 75 with 0.
data[:,2][data[:, 2] < 75] = 0

In [61]:
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])